import type { ProjectPrivateDetails } from "~/types/project";

export const projects: ProjectPrivateDetails[] = [
  {
    id: "1",
    title: "Wefy HTTP Client",
    description: "A modular HTTP client built with fetch, supporting scoped extensions, decorators, and immutability.",
    link: "https://github.com/promise/wefy",
    repo: "https://github.com/promise/wefy",
    for: "Internal Tooling",
    skillsRequired: ["TypeScript", "Fetch API", "Modular Design"],
    collaborators: ["Promise", "Kaur", "Mari"],
    content:
      "Wefy is a type-safe, functional HTTP client designed for modern full-stack apps. It supports scoped middleware, extensions, and decorator chaining.",
    isFeatured: true,
    updatedAt: new Date("2025-06-01"),
    comments: ["Needs tests for decorator chaining.", "Add more examples to docs."],
    isArchived: false,
  },
  {
    id: "2",
    title: "Estonian-English Code-Switching Analyzer",
    description:
      "A research tool to analyze how high school students code-switch between English and Estonian in written texts.",
    for: "School Research",
    skillsRequired: ["Linguistics", "Data Analysis", "React"],
    collaborators: ["Promise"],
    content:
      "This tool uses regex and text segmentation to detect and classify English expressions inside Estonian writing.",
    isFeatured: true,
    updatedAt: new Date("2025-05-18"),
    comments: ["Consider making a Svelte version.", "Upload corpus data to Supabase."],
    isArchived: false,
  },
  {
    id: "3",
    title: "Fastify + Mercurius GraphQL API",
    description: "Typed GraphQL server setup using Mercurius, Fastify, and Vite.",
    link: "https://myapi.dev/graphql",
    repo: "https://github.com/promise/fastify-mercurius",
    for: "Backend Portfolio",
    skillsRequired: ["GraphQL", "TypeScript", "Fastify", "Vite"],
    collaborators: ["Promise", "Reimo"],
    content: "This backend provides a clean GraphQL schema, robust middleware, and full TS support with codegen.",
    isFeatured: false,
    updatedAt: new Date("2025-06-03"),
    comments: ["Add JWT auth.", "Split schema into modules."],
    isArchived: false,
  },
  {
    id: "4",
    title: "Portfolio Remake 2025",
    description: "Minimalistic portfolio remake using Next.js App Router and TailwindCSS.",
    link: "https://promise.dev",
    repo: "https://github.com/promise/portfolio-2025",
    for: "Personal Branding",
    skillsRequired: ["Next.js", "TailwindCSS", "TypeScript"],
    collaborators: ["Promise"],
    content: "A DRY portfolio reading data from JSON blobs for easy updates and improved DX.",
    isFeatured: true,
    updatedAt: new Date("2025-07-01"),
    comments: ["Needs loading skeletons.", "Add dark mode toggle."],
    isArchived: false,
  },
  {
    id: "5",
    title: "Study Tracker App",
    description: "Tracks study sessions, topics, and provides stats for motivation.",
    repo: "https://github.com/promise/study-tracker",
    for: "School Productivity",
    skillsRequired: ["React", "Zustand", "TailwindCSS", "Chart.js"],
    collaborators: ["Promise", "Loviise"],
    content: "Lightweight tracker with tagging, pie charts, and a Pomodoro timer.",
    isFeatured: false,
    updatedAt: new Date("2025-06-18"),
    comments: ["Add CSV export.", "Rewrite chart UI with Recharts."],
    isArchived: false,
  },
  {
    id: "6",
    title: "AI Chat Frontend",
    description: "A chat-like frontend for interfacing with OpenAI’s API.",
    repo: "https://github.com/promise/ai-chat",
    for: "Frontend Experiment",
    skillsRequired: ["React", "OpenAI API", "Streaming"],
    collaborators: ["Promise"],
    content: "Supports real-time streaming with server-sent events and Markdown rendering.",
    isFeatured: false,
    updatedAt: new Date("2025-05-12"),
    comments: ["Token limits not visible to user.", "Add conversation history."],
    isArchived: false,
  },
  {
    id: "7",
    title: "Estonian Verb Conjugator",
    description: "Tool to generate Estonian verb forms and declensions.",
    for: "Language Study",
    skillsRequired: ["Estonian Grammar", "Regex", "TypeScript"],
    collaborators: ["Promise", "Uku"],
    content: "Includes partitive, genitive, plural, and verb forms with logic trees and suffix mapping.",
    isFeatured: true,
    updatedAt: new Date("2025-06-22"),
    comments: ["More error handling.", "Highlight vowel harmony exceptions."],
    isArchived: false,
  },
  {
    id: "8",
    title: "Nõo Embedded Tools UI",
    description: "Control panel for embedded sensors at Nõo Science School.",
    for: "Hackathon",
    skillsRequired: ["React", "Web Serial API", "Chart.js"],
    collaborators: ["Promise", "Martti", "Ingrid"],
    content: "Frontend to connect with Arduino sensors over USB and visualize readings live.",
    isFeatured: false,
    updatedAt: new Date("2025-04-28"),
    comments: ["Need better error states.", "Add debounce to readings."],
    isArchived: false,
  },
  {
    id: "9",
    title: "EduTask CLI Wrapper",
    description: "Wraps around EduTask API to fetch assignments via CLI.",
    for: "Utility",
    skillsRequired: ["Node.js", "Commander", "Fetch API"],
    collaborators: ["Promise"],
    content: "Supports login, listing tasks, checking deadlines, and status.",
    isFeatured: false,
    updatedAt: new Date("2025-05-15"),
    comments: ["Maybe write TUI version in Rust."],
    isArchived: false,
  },
  {
    id: "10",
    title: "AI Grader",
    description: "Grades Estonian essays using OpenAI models and linguistic rules.",
    for: "School",
    skillsRequired: ["OpenAI API", "Estonian NLP", "Prompt Engineering"],
    collaborators: ["Promise", "Reet"],
    content: "Context-aware grading with grammar suggestions, CEFR-based scoring, and model tuning.",
    isFeatured: true,
    updatedAt: new Date("2025-06-10"),
    comments: ["Add rubric customization.", "Log model drift."],
    isArchived: false,
  },
  {
    id: "11",
    title: "MiniKanban",
    description: "A minimal Trello-like kanban board built in React.",
    for: "Frontend Practice",
    skillsRequired: ["React", "TailwindCSS", "Drag and Drop"],
    collaborators: ["Promise"],
    content: "Supports columns, draggable cards, and local storage sync.",
    isFeatured: false,
    updatedAt: new Date("2025-06-29"),
    comments: ["Add Firebase sync option."],
    isArchived: false,
  },
  {
    id: "12",
    title: "Skooli Notes App",
    description: "Note-taking app for students with Markdown and tagging.",
    for: "Student Tools",
    skillsRequired: ["React", "Zustand", "Local Storage"],
    collaborators: ["Promise", "Karl", "Kertu"],
    content: "Offline-first note app that stores notes in local storage with Markdown and tags.",
    isFeatured: false,
    updatedAt: new Date("2025-07-01"),
    comments: ["Add collaborative editing."],
    isArchived: false,
  },
  {
    id: "13",
    title: "SvelteKit Playground",
    description: "A playground site using SvelteKit to explore routing and stores.",
    for: "Framework Experimentation",
    skillsRequired: ["SvelteKit", "TypeScript"],
    collaborators: ["Promise"],
    content: "Learning project to explore reactive stores and advanced routing in SvelteKit.",
    isFeatured: false,
    updatedAt: new Date("2025-06-15"),
    comments: ["Consider porting a component from React."],
    isArchived: false,
  },
  {
    id: "14",
    title: "WebSocket Chat",
    description: "A real-time chat app using WebSockets with Fastify backend.",
    for: "Real-time Demo",
    skillsRequired: ["WebSockets", "Fastify", "React"],
    collaborators: ["Promise", "Ken"],
    content: "Supports room-based chat, presence updates, and reconnection logic.",
    isFeatured: false,
    updatedAt: new Date("2025-06-19"),
    comments: ["Encrypt messages."],
    isArchived: false,
  },
  {
    id: "15",
    title: "Estonian Declension Drill",
    description: "Practice tool for Estonian noun cases with smart hints.",
    for: "Language Study",
    skillsRequired: ["Estonian Morphology", "Svelte", "TypeScript"],
    collaborators: ["Promise"],
    content: "Interactive practice tool that gives plural/partitive/genitive form hints and feedback.",
    isFeatured: false,
    updatedAt: new Date("2025-06-01"),
    comments: ["Add support for irregular words."],
    isArchived: false,
  },
  {
    id: "16",
    title: "Public Transport API Client",
    description: "Client for Estonian transport GTFS data.",
    for: "Open Data Tools",
    skillsRequired: ["Node.js", "GTFS", "Fetch"],
    collaborators: ["Promise"],
    content: "Fetches live schedules, route info, and formats it for visualisation.",
    isFeatured: false,
    updatedAt: new Date("2025-06-11"),
    comments: ["Cache results in local DB."],
    isArchived: false,
  },
  {
    id: "17",
    title: "Blog MDX Platform",
    description: "Static blog using MDX and content layer.",
    for: "Content",
    skillsRequired: ["Next.js", "MDX", "Contentlayer"],
    collaborators: ["Promise"],
    content: "Custom blog platform with component-based MDX and tailwind design system.",
    isFeatured: true,
    updatedAt: new Date("2025-06-30"),
    comments: ["Add RSS support.", "Fix syntax highlighting for code blocks."],
    isArchived: false,
  },
  {
    id: "18",
    title: "CV Generator",
    description: "Generate beautiful CV PDFs from JSON input.",
    for: "Personal Utility",
    skillsRequired: ["React", "PDFKit", "JSON"],
    collaborators: ["Promise"],
    content: "Takes structured JSON input and renders it into a styled printable PDF.",
    isFeatured: false,
    updatedAt: new Date("2025-06-01"),
    comments: ["Add export to DOCX."],
    isArchived: false,
  },
  {
    id: "19",
    title: "FileDrop",
    description: "A minimalist P2P file transfer tool using WebRTC.",
    for: "Utility",
    skillsRequired: ["WebRTC", "React", "Signaling"],
    collaborators: ["Promise"],
    content: "Transfers files browser-to-browser using data channels without uploading to servers.",
    isFeatured: false,
    updatedAt: new Date("2025-06-26"),
    comments: ["Implement drag-and-drop."],
    isArchived: false,
  },
  {
    id: "20",
    title: "Weather Whisper",
    description: "A tiny app to show poetic weather descriptions based on OpenWeatherMap.",
    for: "Just for Fun",
    skillsRequired: ["React", "API Integration", "UX"],
    collaborators: ["Promise"],
    content: "Shows the weather but makes it sound like a medieval bard wrote it.",
    isFeatured: false,
    updatedAt: new Date("2025-06-30"),
    comments: ["Add Estonian translations."],
    isArchived: false,
  },
];
